version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - ru: echo "hello world" # run the `echo` command
      - run: echo "Riches A Kul Boy"